# Generated by Django 4.1.1 on 2022-11-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'permissions': [('eriell_view_report_and_rest', 'Can view report and CRUD Mark')], 'verbose_name': 'Mark', 'verbose_name_plural': 'Marks'},
        ),
        migrations.AlterField(
            model_name='mark',
            name='grade',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=50),
        ),
    ]
